In [85]:
import pandas as pd
import math
import numpy as np
import matplotlib.pyplot as plt

In [86]:
df=pd.read_csv("ins_data.csv")

x=df.drop(columns="bought_insurance")
f=x.to_numpy()
label=df["bought_insurance"]
label=label.to_numpy()
label=label.reshape(28,1)
bias=np.random.rand(1)
df

    age  affordibility  bought_insurance
0    22              1                 0
1    25              0                 0
2    47              1                 1
3    52              0                 0
4    46              1                 1
5    56              1                 1
6    55              0                 0
7    60              0                 1
8    62              1                 1
9    61              1                 1
10   18              1                 0
11   28              1                 0
12   27              0                 0
13   29              0                 0
14   49              1                 1
15   55              1                 1
16   25              0                 1
17   58              1                 1
18   19              0                 0
19   18              1                 0
20   21              1                 0
21   26              0                 0
22   40              1                 1
23   45              1                 1
24   50              1                 1
25   54              1                 1
26   23              1                 0
27   46              1                 0

In [87]:
def sigmoid (x):
  return 1/(1+np.exp(-x))

In [88]:
def sigmoid_der(x):
    return sigmoid(x) * (1-sigmoid(x))

In [89]:
w=np.random.rand(2,1) 
n=0.05

In [90]:
for ep in range(10):
    inp=f
    sum=np.dot(f,w)+bias
    z=sigmoid(sum)
    error=z-label
    print(error.sum())
    dpred=error
    dz=sigmoid_der(z)
    delz=dpred*dz
    inp=sum.T
    w-=n*np.dot(inp,delz)
    
    for num in delz:
        bias-=n*num

13.999903027388237

TypeError: bad operand type for unary -: 'vectorize'

In [ ]:
x

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
affordibility,1,0,1,0,1,1,0,0,1,1,...,0,1,1,0,1,1,1,1,1,1
age,22,25,47,52,46,56,55,60,62,61,...,19,18,21,26,40,45,50,54,23,46